<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <NoWarn>$(NoWarn);NU1901</NoWarn>
    <SpaRoot>..\routesapp.client</SpaRoot>
    <SpaProxyLaunchCommand>npm run dev</SpaProxyLaunchCommand>
    <SpaProxyServerUrl>https://localhost:53424</SpaProxyServerUrl>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\assets\index-BYkCa5Zg.css" />
    <Content Remove="wwwroot\assets\index-CSUw1k-L.js" />
    <Content Remove="wwwroot\favicon.svg" />
    <Content Remove="wwwroot\icons.svg" />
    <Content Remove="wwwroot\index.html" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.SpaProxy">
      <Version>10.*-*</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\routesapp.client\routesapp.client.esproj">
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\assets\index-BYkCa5Zg.css" />
    <None Include="wwwroot\assets\index-CSUw1k-L.js" />
    <None Include="wwwroot\favicon.svg" />
    <None Include="wwwroot\icons.svg" />
    <None Include="wwwroot\index.html" />
  </ItemGroup>

</Project>
